[workspace]
resolver = "3"
members = [
    "app",
    "shared_view",
    "experiments/tabletop_sound",
    "experiments/triangulation_navigator",
]

[workspace.dependencies]
egui = "0.36.1"
eframe = "0.36.1"
egui_dock = "0.21.1"
egui-video = "0.9.0"
glam = "0.33.2"
rand = "0.10.2"

shared_view = { path = "shared_view" }
