[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
egui.workspace = true
eframe.workspace = true
egui_dock.workspace = true
egui-video.workspace = true
glam.workspace = true
rand.workspace = true
glow.workspace = true

tabletop_sound = { path = "../experiments/tabletop_sound" }
triangulation_navigator = { path = "../experiments/triangulation_navigator" }
